In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

,age,affordibility,bought_insurance
0,22,1,0
1,25,0,0
2,47,1,1
3,52,0,0
4,46,1,1


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']], df[['bought_insurance']], test_size=0.2,random_state=2)

In [4]:
len(X_train)

22

In [5]:
len(X_test)

6

In [10]:
X_train_scalled = X_train.copy()
X_train_scalled['age'] = X_train_scalled['age'] / 100

X_test_scalled = X_test.copy()
X_test_scalled['affordibility'] = X_test_scalled['affordibility'] / 100

In [11]:
X_train_scalled

,age,affordibility
16,0.25,0
6,0.55,0
3,0.52,0
21,0.26,0
26,0.23,1
25,0.54,1
12,0.27,0
4,0.46,1
10,0.18,1
5,0.56,1


In [ ]:
model = keras.Sequential([
    keras.layers.Dense
    (
    1, 
    input_shape=(2,),
    activation = 'sigmoid',
    kernel_initializer='ones',
    bias_initializer='zeros'
    )
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_scalled, y_train, epochs=5000)

C:\Users\Mohd Zaid\anaconda3\envs\deep-learning\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 642ms/step - accuracy: 0.5000 - loss: 0.7146
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.7142
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7138
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7135
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7131
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7127
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7123
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7119
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7116
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7112
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.7108
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy

In [8]:
model.evaluate(X_test_scalled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 220ms/step - accuracy: 0.5000 - loss: 51.8675


[51.86748123168945, 0.5]

In [12]:
X_test_scalled

,age,affordibility
1,25,0.00
0,22,0.01
14,49,0.01
9,61,0.01
19,18,0.01
17,58,0.01


In [14]:
model.predict(X_test_scalled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [15]:
y_test

,bought_insurance
1,0
0,0
14,1
9,1
19,0
17,1


In [16]:
coef, intercept = model.get_weights()
coef, intercept

(array([[4.9196653],
        [1.4286094]], dtype=float32),
 array([-2.8673074], dtype=float32))

In [20]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def prediction_function(age, affordability):
    weighted_sum = coef[0][0] * age + coef[0][1] * affordability + intercept[0]
    return sigmoid(weighted_sum)

In [21]:
prediction_function(.47, 1)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [22]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [28]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [29]:
gradient_descent(X_train_scalled['age'],X_train_scalled['affordibility'],y_train,1000, 0.4631)

ValueError: Unable to coerce to Series, length must be 1: given 22

In [ ]:
coef, intercept