In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [4]:
# Slicing (Extracting Parts of an Array)

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [6]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40  50]


In [7]:
# fancy indexing

arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [8]:
# boolean indexing

arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


Exercises for Practice
Create a 3×3 array filled with random numbers and print its shape.
Convert an array of floats [1.1, 2.2, 3.3] into integers.
Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
Reshape a 1D array of size 9 into a 3×3 matrix.
Use boolean masking to filter numbers greater than 50 in an array.

In [11]:
arr1 = np.array([[[2,4,6,],[5,3,6],[33,6,8]]])

print("Shape:", arr.shape)

Shape: (1, 3, 3)


In [12]:
arr1 = np.array([[[2,4,6,],[5,3,6],[33,6,8]]], dtype=np.float32)

arr1

array([[[ 2.,  4.,  6.],
        [ 5.,  3.,  6.],
        [33.,  6.,  8.]]], dtype=float32)

In [13]:
arr1 = arr1.astype(np.int32)
arr1

array([[[ 2,  4,  6],
        [ 5,  3,  6],
        [33,  6,  8]]], dtype=int32)

In [14]:
even = arr1 % 2 == 0

print(arr[even])

[2 4 6 6 6 8]


In [16]:
reshaped = arr1.reshape(9)

print("Reshape:", reshaped)
print("shape:", arr1.shape)

Reshape: [ 2  4  6  5  3  6 33  6  8]
shape: (1, 3, 3)


In [18]:
mask = arr1>5
print(arr1[mask])

[ 6  6 33  6  8]
