In [2]:
import numpy as np

In [3]:
arr = np.array([2,3,44,5,6])

In [5]:
np.mean(arr) # Compute the mean (average) of an array.

np.float64(12.0)

In [6]:
# Compute the standard deviation of an array.
np.std(arr)

np.float64(16.06237840420901)

In [7]:
# Compute the variance of an array.
np.var(arr)

np.float64(258.0)

In [8]:
# Compute the minimum value of an array.
np.min(arr)

np.int64(2)

In [9]:
# Compute the maximum value of an array.
np.max(arr)

np.int64(44)

In [10]:
# Compute the sum of all elements in an array.
np.sum(arr)

np.int64(60)

In [11]:
# Compute the product of all elements in an array.
np.prod(arr)

np.int64(7920)

In [12]:
# Compute the median of an array.
np.median(arr)

np.float64(5.0)

In [14]:
# np.percentile() – Compute the percentile of an array.
np.percentile(arr,50)

np.float64(5.0)

In [15]:
# np.argmin() – Return the index of the minimum value in an array.

np.argmin(arr)

np.int64(0)

In [16]:
# np.argmax() – Return the index of the maximum value in an array.

np.argmax(arr)

np.int64(2)

In [20]:
# np.corrcoef() – Compute the correlation coefficient matrix of two arrays.
arr2 = np.array([2,45,7,86,4])
np.corrcoef(arr, arr2)

array([[ 1.        , -0.31501135],
       [-0.31501135,  1.        ]])

In [21]:
# np.unique() – Find the unique elements of an array.

np.unique(arr)

array([ 2,  3,  5,  6, 44])

In [22]:
# np.diff() – Compute the n-th differences of an array.

np.diff(arr)

array([  1,  41, -39,   1])

In [23]:
# np.cumsum() – Compute the cumulative sum of an array.

np.cumsum(arr)



array([ 2,  5, 49, 54, 60])

In [24]:
# np.linspace() – Create an array with evenly spaced numbers over a specified interval.

np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
# np.log() – Compute the natural logarithm of an array.

np.log(arr)

array([0.69314718, 1.09861229, 3.78418963, 1.60943791, 1.79175947])

In [26]:
# np.exp() – Compute the exponential of an array.

np.exp(arr)

array([7.38905610e+00, 2.00855369e+01, 1.28516001e+19, 1.48413159e+02,
       4.03428793e+02])